# Generated by Django 4.1.4 on 2022-12-07 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('count_of_workers', models.IntegerField()),
                ('appointment', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('rank', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('count_of_workers', models.IntegerField()),
                ('appointment', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('rank', models.CharField(max_length=200)),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_forms.brigade')),
            ],
        ),
        migrations.AddField(
            model_name='brigade',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_forms.cities'),
        ),
    ]
