# Generated by Django 4.1.4 on 2022-12-07 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
