# Generated by Django 4.1.4 on 2022-12-07 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_forms', '0002_alter_cities_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='parnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='app_forms.cities', verbose_name='Родительская категория'),
        ),
    ]
