# Generated by Django 4.1.4 on 2022-12-07 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_forms', '0003_cities_parnet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='parnet',
            new_name='parent',
        ),
    ]
